name: Run Vulnerability Report Script

on:
  # schedule:
  #  - cron: '0 0 * * *'
  push:
    branches: main
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  

    - name: Install dependencies
      run: |
        pip install requests boto3

    - name: Run script
      run: python notificator.py
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        TO_ADDRESSES: ${{ secrets.TO_ADDRESSES }}
        FROM_ADDRESSES: ${{ secrets.FROM_ADDRESSES }}
